version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/node
    overwrites: true
permissions:
  - object: /home/ubuntu/node/codedeploy
    pattern: "*.sh"
    owner: root
    group: root
    mode: 755
    type:
      - file

hooks:
  BeforeInstall:
    - location: codedeploy/before_install.sh
      timeout: 300
  AfterInstall:
    - location: codedeploy/after_install.sh
      timeout: 600
  ApplicationStart:
    - location: codedeploy/application_start.sh
      timeout: 120
  ApplicationStop:
    - location: codedeploy/application_stop.sh
      timeout: 120
  ValidateService:
    - location: codedeploy/validate_service.sh
      timeout: 60